Repository WePlanPlans/WPP_BE, pull requests merged in 2024-01, with the labels that each got.

#31 Feat : 여행지 키워드 조회시, 여행지 타입에 해당하는 키워드만 리턴되게 수정
  src/main/java/org/tenten/tentenbe/domain/review/repository/KeywordRepository.java
  src/main/java/org/tenten/tentenbe/domain/review/service/ReviewService.java
Labels: enhancement

#32 Be 25 login signup
  build.gradle
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/LoginRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/SignUpRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/CheckResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/LoginResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/MemberDto.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/repository/MemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/token/dto/TokenDTO.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/ExpireAccessTokenException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/LogoutMemberException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/TokenException.java
  src/main/java/org/tenten/tentenbe/global/common/constant/JwtConstants.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
  src/main/java/org/tenten/tentenbe/global/security/filter/TempFilter.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/CustomLogoutSuccessHandler.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/UserDetailService.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/model/RefreshToken.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/org/tenten/tentenbe/global/security/token/TempToken.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
  src/main/java/org/tenten/tentenbe/global/util/TempUtil.java
Labels: enhancement

#33 Feat: 여정 생성 및 조회 API 기능 구현
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/tour/model/TourItem.java
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripCreateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripCreateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/TripItem.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripMemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripUserRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: enhancement

#34 Be 35 my page
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/exception/UserNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/response/MemberReviewResponse.java
  src/main/java/org/tenten/tentenbe/domain/review/repository/KeywordRepository.java
  src/main/java/org/tenten/tentenbe/domain/review/repository/ReviewRepository.java
  src/main/java/org/tenten/tentenbe/domain/review/service/ReviewService.java
  src/main/java/org/tenten/tentenbe/domain/tour/dto/response/TourDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: enhancement

#35 Be 24 security
  build.gradle
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/LoginRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/SignUpRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/CheckResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/LoginResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/MemberDto.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/exception/UserNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/repository/MemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/response/MemberReviewResponse.java
  src/main/java/org/tenten/tentenbe/domain/review/repository/ReviewRepository.java
  src/main/java/org/tenten/tentenbe/domain/token/dto/TokenDTO.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/ExpireAccessTokenException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/LogoutMemberException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/TokenException.java
  src/main/java/org/tenten/tentenbe/global/common/constant/JwtConstants.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
  src/main/java/org/tenten/tentenbe/global/security/filter/TempFilter.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/CustomLogoutSuccessHandler.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/UserDetailService.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/model/RefreshToken.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/org/tenten/tentenbe/global/security/token/TempToken.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
  src/main/java/org/tenten/tentenbe/global/util/TempUtil.java
  src/main/resources/application-prod.yml
Labels: enhancement

#36 Develop
  build.gradle
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/LoginRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/SignUpRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/CheckResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/LoginResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/MemberDto.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/exception/UserNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/repository/MemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/response/MemberReviewResponse.java
  src/main/java/org/tenten/tentenbe/domain/review/repository/ReviewRepository.java
  src/main/java/org/tenten/tentenbe/domain/token/dto/TokenDTO.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/ExpireAccessTokenException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/LogoutMemberException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/TokenException.java
  src/main/java/org/tenten/tentenbe/global/common/constant/JwtConstants.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
  src/main/java/org/tenten/tentenbe/global/security/filter/TempFilter.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/CustomLogoutSuccessHandler.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/UserDetailService.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/model/RefreshToken.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/org/tenten/tentenbe/global/security/token/TempToken.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
  src/main/java/org/tenten/tentenbe/global/util/TempUtil.java
Labels: enhancement

#37 Feat: JWT 시크릿 키 환경변수 적용
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
Labels: enhancement

#38 Fix: JWT 시크릿 키 환경변수 적용
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
Labels: bug

#40 Fix: 스웨거 Url 오류 수정
  src/main/java/org/tenten/tentenbe/config/SwaggerConfig.java
Labels: bug

#41 Refactor : 리프레쉬 토큰 schema.sql에 ddl 추가
  .http/Review.http
  src/main/java/org/tenten/tentenbe/global/security/jwt/model/RefreshToken.java
  src/main/resources/schema.sql
Labels: enhancement

#43 Fix: Tour API 변경된 요구사항 적용하여 코드 수정
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
  src/main/java/org/tenten/tentenbe/domain/tour/dto/response/TourSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: enhancement

#44 Fix: Tour API 변경된 요구사항 적용하여 코드 수정
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
  src/main/java/org/tenten/tentenbe/domain/tour/dto/response/TourSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: enhancement

#46 Develop
  src/main/java/org/tenten/tentenbe/config/SwaggerConfig.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/UserDetailService.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
Labels: bug

#47 Be 40 upload image
  build.gradle
  src/main/java/org/tenten/tentenbe/config/S3Config.java
  src/main/java/org/tenten/tentenbe/global/s3/ImageUploadDto.java
  src/main/java/org/tenten/tentenbe/global/s3/S3Controller.java
  src/main/java/org/tenten/tentenbe/global/s3/S3Uploader.java
  src/main/resources/application-prod.yml
Labels: enhancement

#48 S3
  build.gradle
  src/main/java/org/tenten/tentenbe/config/S3Config.java
  src/main/java/org/tenten/tentenbe/global/s3/ImageUploadDto.java
  src/main/java/org/tenten/tentenbe/global/s3/S3Controller.java
  src/main/java/org/tenten/tentenbe/global/s3/S3Uploader.java
  src/main/resources/application-prod.yml
Labels: enhancement

#49 Fix: ELB에 S3 환경변수 설정
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: bug

#50 Fix: 프로필 이미지 업로드 api 위치 변경
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/global/s3/S3Controller.java
Labels: bug, enhancement

#51 Develop
  src/main/java/org/tenten/tentenbe/config/WebConfig.java
  src/main/java/org/tenten/tentenbe/domain/comment/controller/CommentController.java
  src/main/java/org/tenten/tentenbe/domain/comment/service/CommentService.java
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: enhancement

#52 Be 41 liked
  src/main/java/org/tenten/tentenbe/domain/liked/controller/LikedController.java
  src/main/java/org/tenten/tentenbe/domain/liked/exception/ConflictException.java
  src/main/java/org/tenten/tentenbe/domain/liked/model/LikedItem.java
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/liked/service/LikedService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/tour/exception/TourNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/tour/model/TourItem.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: enhancement

#53 Feature Liked & Refactor Review
  src/main/java/org/tenten/tentenbe/domain/liked/controller/LikedController.java
  src/main/java/org/tenten/tentenbe/domain/liked/exception/ConflictException.java
  src/main/java/org/tenten/tentenbe/domain/liked/model/LikedItem.java
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/liked/service/LikedService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/review/service/ReviewService.java
  src/main/java/org/tenten/tentenbe/domain/tour/exception/TourNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/tour/model/TourItem.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
Labels: enhancement

#54 Refactor : 제주도 -> 제주로 수정
  src/main/java/org/tenten/tentenbe/global/common/enums/Region.java
Labels: enhancement

#55 Refactor: 현재 로그인되어 있는 회원 Id 추가
  src/main/java/org/tenten/tentenbe/domain/comment/controller/CommentController.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/review/controller/ReviewController.java
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
Labels: enhancement

#57 Be 35 my page
  src/main/java/org/tenten/tentenbe/domain/auth/exception/DuplicateNicknameException.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/tour/dto/response/TourSimpleResponse.java
Labels: enhancement

#58 Develop
  src/main/java/org/tenten/tentenbe/domain/auth/exception/DuplicateNicknameException.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/tour/dto/response/TourSimpleResponse.java
Labels: enhancement

#61 Refactor : 리뷰 평점 소수점도 가능하게 수정 & 여행지 관심 상품에 담겼는지 정보 변경
  src/main/java/org/tenten/tentenbe/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/response/MemberReviewResponse.java
  src/main/java/org/tenten/tentenbe/domain/review/dto/response/ReviewInfo.java
  src/main/java/org/tenten/tentenbe/domain/review/model/Review.java
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
  src/main/resources/data/Member.sql
  src/main/resources/data/TourItemReviewKeyword.sql
  src/main/resources/schema.sql
Labels: enhancement

#62 Refactor : 테스트 빌드 오류 수정
  src/test/java/org/tenten/tentenbe/domain/comment/service/CommentServiceTest.java
Labels: bug

#63 Refactor : 여행 상품 좋아요 확인 로직 수정
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: bug

#64 Refactor : 로컬에서 스웨거 테스트를 위한 RefreshToken 데이터 추가
  src/main/resources/data/Member.sql
Labels: enhancement

#65 Refactor&Fix: 인기 여행지 조회 API 로직 변경 및 쿼리 성능 개선
  src/main/java/org/tenten/tentenbe/domain/tour/controller/TourController.java
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/tour/service/TourService.java
Labels: enhancement

#66 Refactor : 여행 아이템 리뷰수, 좋아요수, 칼럼에서 읽어오는 값으로 변경
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
Labels: enhancement

#67 Refactor : 인기 여행지 조회시, 좋아요 여부 리턴되게 수정
  src/main/java/org/tenten/tentenbe/domain/tour/repository/TourItemRepository.java
Labels: enhancement

#68 Be 51 auth biz update
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/LoginRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/SignUpRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/PasswordUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/SurveyUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: enhancement

#69 Be 51 auth biz update
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/LoginRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/request/SignUpRequest.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/PasswordUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/SurveyUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: enhancement

#70 Be 51 auth biz update
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/CustomLogoutSuccessHandler.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/repository/RefreshTokenRepository.java
Labels: bug, enhancement

#71 Develop
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/CustomLogoutSuccessHandler.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/repository/RefreshTokenRepository.java
Labels: bug, enhancement

#72 Fix: 회원 조회 수정 -> 여행 취향 설정 데이터 변경
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberDetailResponse.java
Labels: bug

#73 Docs&Refactor: 여정 기능 추가 및 DB 컬럼 이름 변경
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripInfoUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripLikedItemRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripInfoUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripLikedSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/TripLikedItemPreference.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: documentation

#74 Develop
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripInfoUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripLikedItemRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripInfoUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripLikedSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/TripLikedItemPreference.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: documentation

#77 Refactor : JwtFilter CORS 수정
  .http/Tour.http
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
Labels: enhancement

#78 Be 51 auth biz update
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/dto/response/SignUpResponse.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: enhancement

#83 Fix: 토큰이 없는 상태에서 요청 시 예외 처리
  src/main/java/org/tenten/tentenbe/domain/token/exception/AccessTokenNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/ExpireAccessTokenException.java
  src/main/java/org/tenten/tentenbe/domain/token/exception/RefreshTokenNotFoundException.java
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
Labels: enhancement

#84 Fix: SecurityConfig 수정 (requestMatchers 추가)
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/tenten/tentenbe/global/util/SecurityUtil.java
Labels: bug, enhancement

#86 Develop
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: bug, enhancement

#87 Fix: SecurityConfig 수정 (requestMatchers 정보수정)
  src/main/java/org/tenten/tentenbe/domain/token/exception/InvalidRefreshTokenException.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/filter/JwtFilter.java
  src/main/java/org/tenten/tentenbe/global/security/jwt/JwtTokenProvider.java
Labels: bug, enhancement

#88 Fix: SecurityConfig 수정 (스웨거)
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: bug

#89 Develop
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
Labels: bug

#90 Fix: SecurityConfig 수정 (스웨거)
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: bug

#91 Fix: 로그아웃 리다이렉트 제거 후 로직 위치 변경
  src/main/java/org/tenten/tentenbe/domain/auth/controller/AuthController.java
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: enhancement

#94 Be 55 feat trip api develop
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripLikedSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/exception/TripLikeItemPreferenceException.java
  src/main/java/org/tenten/tentenbe/domain/trip/exception/TripLikedItemException.java
  src/main/java/org/tenten/tentenbe/domain/trip/exception/TripMemberException.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/TripLikedItemPreference.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripLikedItemPreferenceRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripLikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripMemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: enhancement

#97 Fix: TripStatus 컬럼 DB에서 삭제 및 TripStatus 로직 수정
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/java/org/tenten/tentenbe/global/common/enums/TripStatus.java
  src/main/resources/schema.sql
Labels: enhancement

#98 Fix: TripStatus 컬럼 DB에서 삭제 및 TripStatus 로직 수정
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/java/org/tenten/tentenbe/global/common/enums/TripStatus.java
  src/main/resources/schema.sql
Labels: enhancement

#99 Refactor : 리뷰, 댓글 작성시 로그인 여부 포함 추가
  src/main/java/org/tenten/tentenbe/domain/comment/controller/CommentController.java
  src/main/java/org/tenten/tentenbe/domain/review/controller/ReviewController.java
Labels: enhancement

#100 Be 51 member update
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/liked/service/LikedService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/PasswordUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/exception/UserNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: bug, enhancement

#101 Develop
  src/main/java/org/tenten/tentenbe/domain/auth/service/AuthService.java
  src/main/java/org/tenten/tentenbe/domain/liked/service/LikedService.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/dto/request/PasswordUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/member/exception/UserNotFoundException.java
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: bug, enhancement

#105 Develop
  .github/workflows/deploy.yml
  src/main/java/org/tenten/tentenbe/domain/review/repository/KeywordRepository.java
Labels: enhancement

#106 Refactor : KeywordTotalCount 계산 방식 변경
  src/main/java/org/tenten/tentenbe/domain/review/service/ReviewService.java
Labels: enhancement

#113 Fix: 쿠키삭제 설정 Secure 추가
  src/main/java/org/tenten/tentenbe/domain/member/repository/MemberRepository.java
  src/main/java/org/tenten/tentenbe/global/common/enums/AgeType.java
  src/main/java/org/tenten/tentenbe/global/security/oauth/OAuth2UserService.java
  src/main/java/org/tenten/tentenbe/global/util/CookieUtil.java
  src/main/resources/application-prod.yml
Labels: bug, enhancement

#116 Refactor : 여정 생성시 기본비용값 초기화
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#117 Be 70 fix prefer develop
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberSimpleInfo.java
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyMemberResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#118 Develop
  src/main/java/org/tenten/tentenbe/domain/member/dto/response/MemberSimpleInfo.java
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripDetailResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyMemberResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSurveyResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#119 Hotfix: 나의 여정목록 조회시 Pagenation 제거
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#123 Fix : securityConfig 에 리다이렉트 주소 수정
  src/main/java/org/tenten/tentenbe/domain/member/model/Member.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/TripItem.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/java/org/tenten/tentenbe/global/common/enums/Transportation.java
  src/main/java/org/tenten/tentenbe/global/converter/MapConverter.java
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
  src/main/java/org/tenten/tentenbe/global/security/oauth/OAuth2UserService.java
  src/main/java/org/tenten/tentenbe/global/security/oauth/OAuthLoginSuccessHandler.java
  src/main/resources/application-prod.yml
  src/main/resources/schema.sql
Labels: bug, enhancement

#124 Be 73 fix trip member develop
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/JoinTripRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripCreateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripInfoUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripInfoUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripLikedSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripMembersResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripLikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: enhancement

#125 Fix: Trip 테이블에 암호화된 비밀번호 컬럼 추가
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/JoinTripRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripCreateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripInfoUpdateRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripInfoUpdateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripLikedSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripMembersResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripLikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/resources/schema.sql
Labels: enhancement

#126 Refactor : Trip 생성시 map 디폴트 생성 추가
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#127 Feat: 관심 여행지 조회 시 카테고리 별 조회 기능 추가
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/controller/MemberController.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
Labels: enhancement

#128 Hotfix: 회원 편집권한 검증 로직 변경
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#129 Refactor: participant -> join 으로 변수명 변경
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/JoinTripRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripItemRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripItemResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripMemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#130 Develop
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/JoinTripRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/request/TripItemRequest.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripItemResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripMemberRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#132 Refactor: 쿼리 메서드를 이용한 가독성 향상 및 성능 최적화
  src/main/java/org/tenten/tentenbe/domain/liked/repository/LikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/member/service/MemberService.java
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripAuthorityResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/model/Trip.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: bug, enhancement

#133 Refactor : 암호화 알고리즘 SHA-256으로 수정
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
  src/main/java/org/tenten/tentenbe/global/util/EncryptUtil.java
Labels: enhancement

#134 Refactor : 여정 아이디 암호화된 문자열 값으로 수정
  src/main/java/org/tenten/tentenbe/domain/trip/controller/TripController.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripAuthorityResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripCreateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripItemResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripLikedItemRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#135 Docs : TripId 스웨거 작성
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripCreateResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripItemResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
Labels: enhancement

#136 Hotfix: 우리의 취향 조회 API 기능 수정
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#137 Refactor : 멤버 탈퇴시 실시간 편집에도 반영되게 수정
  src/main/java/org/tenten/tentenbe/domain/trip/service/TripService.java
Labels: enhancement

#138 Fix: 여정목록을 조회할때, numberOfTripMember 응답값 추가
  src/main/java/org/tenten/tentenbe/domain/trip/dto/response/TripSimpleResponse.java
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
Labels: enhancement

#139 Refactor : count = 0 인 tourKeyword 제거
  src/main/java/org/tenten/tentenbe/domain/review/repository/KeywordRepository.java
Labels: enhancement

#140 Refactor: 여정목록 조회 시 기본 썸네일 사진 변경
  src/main/java/org/tenten/tentenbe/domain/trip/repository/TripRepository.java
Labels: enhancement

#144 Refactor: 많은 url 정보들을 관리하기 쉽게 배열로 관리
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: enhancement

#145 Develop
  README.md
  src/main/java/org/tenten/tentenbe/global/security/SecurityConfig.java
Labels: enhancement
